version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands: 
      - echo "installing"
  pre_build:
    commands:
      - echo "waiting"
  build:
    commands:
      - echo "building"
  post_build:
    commands:
      - echo "done"
artifacts:
  files:
    - '**/*'
  base-directory: base-location
  name: dev-artifact
  discard-paths: no