apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: starwars-stage
  labels:
    app: starwars-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starwars-stage
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: starwars-stage
        tier: starwars-stage
    spec:
      containers:
      - name: starwars-stage
        image: evgen66rus/devops_django_stage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: starwars-stage
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
          - name: uwsgi
            mountPath: /var/log/uwsgi/
      - name: beat-manual
        image: elastic/filebeat:7.8.0
        command: ["sh", "-c", "chmod -R 755 /tmp/"]
        args: [
          "-c", "/etc/filebeat/filebeat.yml",
          "-e"
        ]
        volumeMounts:
          - name: beat-manual-config
            mountPath: /etc/filebeat/
          - name: uwsgi
            mountPath: /tmp/
      volumes:
        - name: beat-manual-config
          configMap:
            name: beat-manual-config
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: uwsgi
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: starwars-stage
  labels:
    app: starwars-stage
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: starwars-stage
    tier: starwars-stage
  type: LoadBalancer
