# Generated by Django 3.2 on 2021-04-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('id_num', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Characters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gravity', models.CharField(blank=True, max_length=50, null=True)),
                ('climate', models.CharField(blank=True, max_length=50, null=True)),
                ('residents', models.ManyToManyField(blank=True, null=True, to='finaltask.Character')),
            ],
            options={
                'verbose_name_plural': 'Planets',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='homeworld',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finaltask.planet'),
        ),
    ]
