# Generated by Django 3.2 on 2021-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='residents',
            field=models.ManyToManyField(to='finaltask.Character'),
        ),
    ]
