# Generated by Django 3.2 on 2021-04-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finaltask', '0002_alter_planet_residents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='homeworld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaltask.planet'),
        ),
    ]
