# Generated by Django 3.2 on 2021-04-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finaltask', '0003_alter_character_homeworld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='id_num',
        ),
        migrations.AlterField(
            model_name='character',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finaltask.planet'),
        ),
    ]
