# Generated by Django 3.2 on 2021-04-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finaltask', '0004_auto_20210425_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='homeworld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaltask.planet'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='residents',
            field=models.ManyToManyField(blank=True, to='finaltask.Character'),
        ),
    ]
