# Generated by Django 3.2 on 2021-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltask', '0005_auto_20210425_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='homeworld',
            field=models.CharField(max_length=50),
        ),
    ]
