# Generated by Django 3.2 on 2021-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltask', '0007_auto_20210425_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='residents',
            field=models.ManyToManyField(blank=True, to='finaltask.Character'),
        ),
    ]
