# Generated by Django 3.2 on 2021-04-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finaltask', '0008_alter_planet_residents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='residents',
        ),
    ]
